name: Build and Test Python Bindings

on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libjpeg9

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy setuptools wheel pybind11

    - name: Update submodules
      run: git submodule update --init

    - name: Build the Python bindings
      run: |
        cd python-bindings
        python setup.py bdist_wheel && pip install dist/*.whl

    - name: Test the build
      run: |
        cd python-bindings
        python example.py

    - name: Run unit tests
      run: |
        cd python-bindings
        echo "No unit tests for Linux yet"

  build-windows:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Cache vcpkg
      uses: actions/cache@v4
      with:
        path: |
          vcpkg
          !vcpkg/.git
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('vcpkg.json') }}

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install libjpeg-turbo
      run: .\vcpkg\vcpkg install libjpeg-turbo

    - name: Install pthreads
      run: .\vcpkg\vcpkg install pthreads

    - name: Add vcpkg to path
      shell: bash
      run: echo "vcpkg/installed/x64-windows/bin" >> $GITHUB_PATH

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy setuptools wheel pybind11

    - name: Update submodules
      run: git submodule update --init

    - name: Build the Python bindings
      run: |
        cd python-bindings
        python setup.py bdist_wheel
        pip install dist/jsartoolkitNFT-0.0.5-cp38-cp38-win_amd64.whl

    - name: Test the build
      run: |
        cd python-bindings
        python example.py

    - name: Run unit tests
      run: |
        cd python-bindings
        echo "No unit tests for Windows yet"